# Generated by Django 3.0.2 on 2020-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('no_coaches', models.CharField(max_length=100)),
                ('no_players', models.CharField(max_length=100)),
            ],
        ),
    ]
